services:
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_DB=cinema
      - POSTGRES_USER=cinema
      - POSTGRES_PASSWORD=cinema
    ports:
      - 5433:5432