INSERT INTO movie (id, admin, title, gender, producer, release, duration, actors, summary) VALUES
(1,1,'XMEN', 'Super-héros', 'Bryan Signer', 2000, 104, 'Hugh Jackman, Patrick Stewart, Ian McKellen',
'Séparé par la force de ses parents, le jeune Erik Magnus Lehnsherr se découvre détranges pouvoirs sous le coup de la colère : il peut contrôler les métaux. C''est un mutant. Soixante ans plus tard, l''existence des mutants est reconnue mais provoque toujours un vif émoi au sein de la population.'),
(2,1,'STAR WARS', 'Fantasy, science-fiction', 'Georges Lucas', 1977, 121, 'Mark Hamill, Harrison Ford, Carrie Fisher',
'Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler l''âme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel. Pendant ce temps, l''armée de droïdes de l''insatiable Fédération du Commerce a envahi Naboo dans le cadre d''un plan secret des Sith visant à accroître leur pouvoir.'),
(3,1,'HARRY POTTER', 'Roman Fantasy', 'Chris Columbus', 1997,152,'Daniel Radcliffe, Emma Watson, Rupert Grint',
'Orphelin, le jeune Harry Potter peut enfin quitter ses tyranniques oncle et tante Dursley lorsqu''un curieux messager lui révèle qu''il est un sorcier. À 11 ans, Harry va enfin pouvoir intégrer la légendaire école de sorcellerie de Poudlard, y trouver une famille digne de ce nom et des amis, développer ses dons, et préparer son glorieux avenir.'),
(4,1,'LE SEIGNEUR DES ANNEAUX', 'Roman Fantasy', 'Peter Jackson', 2001,178, 'Elijah Wood, Viggo Mortensen, Orlando Bloom',
'Un jeune et timide Hobbit, Frodon Sacquet, hérite d''un anneau magique. Bien loin dêtre une simple babiole, il s''agit d''un instrument de pouvoir absolu qui permettrait à Sauron, le Seigneur des ténèbres, de régner sur la Terre du Milieu et de réduire en esclavage ses peuples. Frodon doit parvenir jusqu''à la Crevasse du Destin pour détruire l''anneau.'),
(5,1,'DUNE', 'Science Fiction', 'Denis Villeneuve', 2021,165, 'Timothée Chalamet, Zendaya, Rebacca Ferguson',
'Paul Atreides, un jeune homme brillant et doué au destin plus grand que lui-même, doit se rendre sur la planète la plus dangereuse de l''univers afin d''assurer l''avenir de sa famille et de son peuple. Cette planète est la source exclusive de la ressource la plus précieuse qui soit pour laquelle des forces sinistres déclenchent un conflit dont seuls ceux sachant maîtriser leurs peurs survivront.'),
(6,1,'INTERSTELLAR', 'Drame, Science Fiction', 'Christopher Nolan', 2014,169,'Matthew McConaughey, Jessica Chastain, Anne Hathaway',
'Dans un proche futur, la Terre est devenue hostile pour l''homme. Les tempêtes de sable sont fréquentes et il n''y a plus que le maïs qui peut être cultivé, en raison d''un sol trop aride. Cooper est un pilote, recyclé en agriculteur, qui vit avec son fils et sa fille dans la ferme familiale.'),
(7,1,'LES TRADUCTEURS', 'Thriller', 'Régis Roinsard', 2019, 105, 'Alew Lawther, Olga Kurylencko, Sara Giraudeau',
'Neuf traducteurs triés sur le volet sont confinés dans un luxueux bunker afin de traduire le dernier roman d''un auteur très connu en un temps record. Mais malgré ces précautions, les dix premières pages du livre sont dévoilées sur Internet.'),
(8,1,'300', 'Péplum, Action, Guerre', 'Zack Snyder', 2006, 117, 'Gérard Butler, Lena Headey, Rodrigo Santoro',
'En 485 avant notre ère, Xerxès succède à Darius Ier sur le trône de l''empire perse. Rapidement, les grandes cités grecques comprennent qu''une nouvelle guerre s''annonce. Athènes, Thèbes, Corinthe et Délos se rallient à Sparte qui dispose de la meilleure armée. En 480, le roi spartiate Léonidas est nommé commandant en chef de cette union militaire de la dernière chance. Lorsque la flotte perse rallie les fantassins de Xerxès, les troupes grecques prennent peur.')
on conflict do nothing;
