INSERT INTO movie (id, admin, title, gender, producer, release, duration, actors, summary) VALUES
(1,1,'XMEN', 'Super-héros', 'Bryan Signer', 2000, 104, 'Hugh Jackman, Patrick Stewart, Ian McKellen',
'Séparé par la force de ses parents, le jeune Erik Magnus Lehnsherr se découvre détranges pouvoirs sous le coup de la colère : il peut contrôler les métaux. C''est un mutant. Soixante ans plus tard, lexistence des mutants est reconnue mais provoque toujours un vif émoi au sein de la population.'),
(2,1,'STAR WARS', 'Fantasy, science-fiction', 'Georges Lucas', 1977, 121, 'Mark Hamill, Harrison Ford, Carrie Fisher',
'Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler lâme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel. Pendant ce temps, larmée de droïdes de linsatiable Fédération du Commerce a envahi Naboo dans le cadre dun plan secret des Sith visant à accroître leur pouvoir.'),
(3,1,'HARRY POTTER', 'Roman Fantasy', 'Chris Columbus', 1997,152,'Daniel Radcliffe, Emma Watson, Rupert Grint',
'Orphelin, le jeune Harry Potter peut enfin quitter ses tyranniques oncle et tante Dursley lorsquun curieux messager lui révèle quil est un sorcier. À 11 ans, Harry va enfin pouvoir intégrer la légendaire école de sorcellerie de Poudlard, y trouver une famille digne de ce nom et des amis, développer ses dons, et préparer son glorieux avenir.'),
(4,1,'LE SEIGNEUR DES ANNEAUX', 'Roman Fantasy', 'Peter Jackson', 2001,178, 'Elijah Wood, Viggo Mortensen, Orlando Bloom',
'Un jeune et timide Hobbit, Frodon Sacquet, hérite dun anneau magique. Bien loin dêtre une simple babiole, il sagit dun instrument de pouvoir absolu qui permettrait à Sauron, le Seigneur des ténèbres, de régner sur la Terre du Milieu et de réduire en esclavage ses peuples. Frodon doit parvenir jusquà la Crevasse du Destin pour détruire lanneau.'),
(5,1,'DUNE', 'Science Fiction', 'Denis Villeneuve', 2021,165, 'Timothée Chalamet, Zendaya, Rebacca Ferguson',
'Paul Atreides, un jeune homme brillant et doué au destin plus grand que lui-même, doit se rendre sur la planète la plus dangereuse de lunivers afin dassurer lavenir de sa famille et de son peuple. Cette planète est la source exclusive de la ressource la plus précieuse qui soit pour laquelle des forces sinistres déclenchent un conflit dont seuls ceux sachant maîtriser leurs peurs survivront.'),
(6,1,'INTERSTELLAR', 'Drame, Science Fiction', 'Christopher Nolan', 2014,169,'Matthew McConaughey, Jessica Chastain, Anne Hathaway',
'Dans un proche futur, la Terre est devenue hostile pour lhomme. Les tempêtes de sable sont fréquentes et il ny a plus que le maïs qui peut être cultivé, en raison dun sol trop aride. Cooper est un pilote, recyclé en agriculteur, qui vit avec son fils et sa fille dans la ferme familiale.'),
(7,1,'LES TRADUCTEURS', 'Thriller', 'Régis Roinsard', 2019, 105, 'Alew Lawther, Olga Kurylencko, Sara Giraudeau',
'Neuf traducteurs tiés sur le volet sont confinés dans un luxueux bunker afin de traduire le dernier roman dun auteur très connu en un temps record. Mais malgré ces précautions, les dix premières pages du livre sont dévoilées sur Internet.'),
(8,1,'300', 'Péplum, Action, Guerre', 'Zack Snyder', 2006, 117, 'Gérard Butler, Lena Headey, Rodrigo Santoro',
'En 485 avant notre ère, Xerxès succède à Darius Ier sur le trône de lempire perse. Rapidement, les grandes cités grecques comprennent quune nouvelle guerre sannonce. Athènes, Thèbes, Corinthe et Délos se rallient à Sparte qui dispose de la meilleure armée. En 480, le roi spartiate Léonidas est nommé commandant en chef de cette union militaire de la dernière chance. Lorsque la flotte perse rallie les fantassins de Xerxès, les troupes grecques prennent peur.')
on conflict do nothing;
