spring.datasource.url=jdbc:postgresql://0.0.0.0:5432/cinema_db
spring.datasource.username=user
spring.datasource.password=password

spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=update
